import type { Lugar } from './types';

/** A.2 — Datos mock para demo sin login/permisos. */
export const DEMO_LUGARES: Lugar[] = [
  {
    id: 'demo-1',
    nombre: 'Cerro San Cristóbal',
    descripcion: 'Parque metropolitano con funicular, mirador y piscinas.',
    categoria: 'aire_libre',
    tipo: 'turistico',
    precio_nivel: 0,
    direccion: 'Pío Nono, Recoleta',
    imagen_url: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?w=800',
    lat: -33.4256,
    lng: -70.6297,
    rating_promedio: 4.6,
    total_reviews: 234,
  },
  {
    id: 'demo-2',
    nombre: 'Mercado Central',
    descripcion: 'Mercado histórico de pescados y mariscos.',
    categoria: 'gastronomia',
    tipo: 'turistico',
    precio_nivel: 2,
    direccion: 'San Pablo 967, Santiago',
    imagen_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    lat: -33.4343,
    lng: -70.6508,
    rating_promedio: 4.3,
    total_reviews: 178,
  },
  {
    id: 'demo-3',
    nombre: 'Museo Bellas Artes',
    descripcion: 'Museo de arte chileno e internacional.',
    categoria: 'cultura',
    tipo: 'turistico',
    precio_nivel: 0,
    direccion: 'José Miguel de la Barra 650',
    imagen_url: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=800',
    lat: -33.437,
    lng: -70.644,
    rating_promedio: 4.7,
    total_reviews: 412,
  },
  {
    id: 'demo-4',
    nombre: 'Feria Pío Nono (sábado)',
    descripcion: 'Feria de artesanos y food trucks cada sábado.',
    categoria: 'nocturno',
    tipo: 'panorama',
    precio_nivel: 1,
    direccion: 'Pío Nono, Bellavista',
    imagen_url: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
    lat: -33.4318,
    lng: -70.6345,
    fecha_inicio: new Date(Date.now() + 2 * 86400000).toISOString(),
    rating_promedio: 4.2,
    total_reviews: 56,
  },
  {
    id: 'demo-5',
    nombre: 'Parque Bicentenario',
    descripcion: 'Parque urbano con lagunas y flamencos.',
    categoria: 'familiar',
    tipo: 'turistico',
    precio_nivel: 0,
    direccion: 'Av. Bicentenario 3800, Vitacura',
    imagen_url: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800',
    lat: -33.3977,
    lng: -70.5857,
    rating_promedio: 4.5,
    total_reviews: 89,
  },
  {
    id: 'demo-6',
    nombre: 'Farellones',
    descripcion: 'Centro de ski en temporada, hiking verano.',
    categoria: 'deporte',
    tipo: 'turistico',
    precio_nivel: 3,
    direccion: 'Camino a Farellones',
    imagen_url: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
    lat: -33.3547,
    lng: -70.3231,
    rating_promedio: 4.8,
    total_reviews: 301,
  },
];
